[package]
name = "cdbs-back"
version = "0.1.0"
authors = ["I_Nosovsky <mananaxep@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15"

actix-web = "3"
actix-cors = "0.5.4"
actix-multipart = "0.3.0"
futures = "0.3.5"

reqwest = { version = "0.10.8", features = ["json"] }

diesel = { version = "1.4", features = ["postgres", "uuidv07", "uuid", "chrono", "r2d2"] }
r2d2 = "0.8"

async-graphql = { version = "2.9.10", default-features = false, features = ["chrono", "uuid"] }
async-graphql-actix-web = "2.9.10"

uuid = { version = "0.8", features = ["serde", "v4"] }
time = "0.3"
chrono = { version = "0.4.19", features = ["serde"] }

lazy_static = "1"
log = "0.4.14"
env_logger ="0.9.0"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

rand = "0.8"
argon2rs = "0.2"
jsonwebtoken = "=7.2.0"

anyhow = "1.0"
thiserror = "1.0"
num = "0.4"
sanitize-filename = "0.3.0"

structopt = "0.3"

regex = "1"

ring = "0.16.20"
sha2 = "0.9.5"
hmac = "0.11.0"
base64 = "0.13.0"
hex = "0.4.3"

digest = "0.9.0"
blake3 = "1.0.0"
bytes = "1"

[dependencies.rusoto_core]
version = "0.47.0"
path = "../rusoto_s3/core"

[dependencies.rusoto_s3]
version = "0.47.0"
path = "../rusoto_s3/services/s3"

[dependencies.rusoto_signature]
version = "0.47.0"
path = "../rusoto_s3/signature"

[dev-dependencies]
actix-rt = "2.2.0"
