[package]
name = "cdbs-back"
version = "0.1.0"
authors = ["I_Nosovskiy <mananaxep@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15"

actix-web = "3"
actix-cors = "0.5.4"
actix-identity = "0.3"
actix-multipart = "0.3.0"
futures = "0.3.5"

diesel = { version = "1.4", features = ["postgres", "uuidv07", "uuid", "chrono", "r2d2"] }
r2d2 = "0.8"

# juniper = "0.14.2"
async-graphql = { version = "2.9.9", default-features = false, features = ["chrono", "uuid"] }
async-graphql-actix-web = "2.9.9"

uuid = { version = "0.7", features = ["serde", "v4"] }
time = "0.2"
chrono = { version = "0.4.19", features = ["serde"] }

lazy_static = "1"
log = "0.4.8"
env_logger ="0.7.1"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

rand = "0.7"
argon2rs = "0.2"
jsonwebtoken = "=7.0.0-alpha.2"

anyhow = "1.0"
thiserror = "1.0"
num = "0.2"
shrinkwraprs = "0.2"
sanitize-filename = "0.3.0"

structopt = "0.3"

regex = "1"

ring = "0.16.20"
sha2 = "0.9.3"

digest = "0.9.0"
blake3 = "0.3.7"
bytes = "1"

[dev-dependencies]
actix-rt = "2.2.0"
reqwest = "0.11.4"
