###
# @name graphqli
GET http://0.0.0.0:3000/


###
# @name registerUser
POST http://0.0.0.0:3000/user/register HTTP/1.1
Content-Type: application/json

{
  	"firstname": "Vans",
  	"lastname": "Bpero",
  	"secondname": "Nado",
  	"nickname": "albane",
  	"email": "bname@somain.com",
  	"password": "password1",
  	"id_type_user": 1,
  	"is_supplier": 0,
  	"orgname": "",
  	"shortname": "",
  	"inn": "",
  	"phone": "",
  	"id_name_cad": 1,
  	"comment": "",
  	"address": "",
  	"time_zone": 3,
  	"position": "",
  	"site_url": "",
  	"uuid_file_info_icon": "",
  	"id_region": 1
}

###
# @name login
POST http://0.0.0.0:3000/user/login HTTP/1.1
Content-Type: application/json

{
  	"nickname": "albane",
  	"password": "password"
}

###
# @name registerRepresetUser
POST http://0.0.0.0:3000/represet/register HTTP/1.1
Content-Type: application/json

{
  	"id_region": 3,
  	"id_representation_type": 1,
  	"name": "additional office",
  	"address": "None str, Kiev",
  	"phone": "+380874487556"
}

###
# @name deleteRepresetUser
POST http://0.0.0.0:3000/represet/delete HTTP/1.1
Content-Type: application/json

{
  	"uuid_represet": "e2095fa6-681e-4051-a55c-30952e4b2cfd"
}

###
# @name addFile
POST http://0.0.0.0:3000/file/add HTTP/1.1
Content-Type: application/json

{
  	"uuid_file": "bc1c2151-86d0-4656-9c9d-d016dd584297",
  	"hash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
  	"filename": "file_child_two.pdd",
  	"id_ext": 1,
  	"filesize": 136.7,
  	"path_file": "/sholder/file/310eb209-373b-45a7-9d81-daabae27c309"
}

###
# @name addComponent
POST http://0.0.0.0:3000/component/add HTTP/1.1
Content-Type: application/json

{
  	"name": "Fluted Knobs – Tapped (Phenolic), Inch",
  	"comment": "Phenolic Plastic",
  	"uuid_component_parent": "a5953fd9-7393-4f1e-a899-06b5e159dbf1",
  	"id_actual_status": 1,
  	"id_component_type": 1,
  	"id_type_access": 1,
  	"is_standard": 0
}

###
# @name addModification
POST http://0.0.0.0:3000/modification/add HTTP/1.1
Content-Type: application/json

{
  	"uuid_component": "a5953fd9-7393-4f1e-a899-06b5e159dbf1",
  	"modification_name": "Head style U - Type X",
  	"id_name_cad": 2,
    "comment": "bottom modification",
  	"uuid_modification_parent": "aba22d59-4f6c-44a4-9a37-2d38f0e577a8",
  	"id_actual_status": 1
}

###
# @name getMyAccount
GET http://0.0.0.0:3000/user/me HTTP/1.1


###
# @name getJwtToken
POST http://0.0.0.0:3000/graphql HTTP/1.1
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query tokenQuery {
    generateToken {
        bearer
    }
}

###
# @name decodeJwtToken

@jwtToken = {{getJwtToken.response.body.$.data.generateToken.bearer}}

POST http://0.0.0.0:3000/graphql HTTP/1.1
Authorization: Bearer {{jwtToken}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query decodeTokenQuery {
    decodeToken {
        email
        iss
        iat
        exp
        sub
    }
}

###
# @name listUsers
POST http://0.0.0.0:3000/graphql HTTP/1.1
Authorization: Bearer {{jwtToken}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query ListUsers {
    users {
        name
        userUuid
        email
        createdAt
    }
}

###
# @name listUsers
# @return "message": "LIMIT must not be negative"
POST http://0.0.0.0:3000/graphql HTTP/1.1
Authorization: Bearer {{jwtToken}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query usersQuery {
  users(limit: -1, offset: 1) {
    uuid
    email
    emailVerified
    idTypeUser
    isSupplier
    firstname
    lastname
    secondname
    nickname
    orgname
    shortname
    inn
    phone
    idNameCad
    comment
    address
    timeZone
    position
    siteUrl
    uuidFileInfoIcon
    idRegion
    createdAt
  }
}

###
# @name listRepreset
# @return "message": "LIMIT must not be negative"
POST http://0.0.0.0:3000/graphql HTTP/1.1
Authorization: Bearer {{jwtToken}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query represetQuery {
  userRepreset(limit: -1, offset: 1) {
    uuid
    uuidUser
    idRegion
    name
    phone
    idRepresentationType
  }
}

###
# @name listRepresetSelectUser
POST http://0.0.0.0:3000/graphql HTTP/1.1
Authorization: Bearer {{jwtToken}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query selectrepresetQuery {
  userRepreset(uuidUserSearch: "68b8281a-d19c-4d4b-88eb-6fd4a2afde1b", limit: -1, offset: 1) {
    uuid
    uuidUser
    idRegion
    name
    phone
    idRepresentationType
  }
}

###
# @name listFiles
POST http://0.0.0.0:3000/graphql HTTP/1.1
Authorization: Bearer {{jwtToken}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query filesQuery {
  files {
    uuid
    uuidFile
    uuidUserCreate
    filename
    idExt
    createdAt
    filesize
    pathFile
  }
}

###
# @name listComponents
POST http://0.0.0.0:3000/graphql HTTP/1.1
Authorization: Bearer {{jwtToken}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query componentsQuery {
  components {
    uuid
    name
    uuidUser
    comment
    uuidComponentParent
    idActualStatus
    idComponentType
    isDelete
    idTypeAccess
    commentchange
    isStandard
    createdAt
  }
}

###
# @name listComponentModifications
POST http://0.0.0.0:3000/graphql HTTP/1.1
Authorization: Bearer {{jwtToken}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query componentModificationsQuery {
  componentModification {
    uuid
    uuidComponent
    modificationName
    createdAt
    idNameCad
    comment
    uuidModificationParent
    commentchange
    idActualStatus
    isDelete
  }
}

###
# @name logout
GET http://0.0.0.0:3000/user/logout HTTP/1.1

###
