-- Your SQL goes here
INSERT INTO program_ref (name) VALUES
  ('AutoCAD'),
  ('BricsCAD'),
  ('CATIA V4'),
  ('CATIA V5'),
  ('COLLADA'),
  ('Creo'),
  ('DesignSpark Mechanical'),
  ('DraftSight'),
  ('DXF - 2D'),
  ('DXF - 3D'),
  ('EMF'),
  ('FUSION 360'),
  ('GstarCAD'),
  ('HiCAD'),
  ('HOOPS'),
  ('IGES'),
  ('Inventor'),
  ('Inventor LT'),
  ('IRONCAD'),
  ('KOMPAS-3D'),
  ('Mechanical Desktop'),
  ('NX'),
  ('OBJ'),
  ('OFF'),
  ('Panda3D'),
  ('Parasolid 11.1'),
  ('Pro/Engineer Neutral'),
  ('Revit'),
  ('SketchUp'),
  ('Solid Edge'),
  ('SOLIDWORKS'),
  ('SpaceClaim'),
  ('STEP AP203'),
  ('STEP AP214'),
  ('STEP AP242'),
  ('STL'),
  ('T-FLEX'),
  ('Tekla'),
  ('TENADO CAD 3D'),
  ('Three.js'),
  ('TopSolid'),
  ('TurboCAD'),
  ('Universal 3D'),
  ('VDA-FS'),
  ('VRML'),
  ('VTK'),
  ('VX CAD/CAM'),
  ('WMF'),
  ('ZW3D');

INSERT INTO extension_ref (extension, id_program) VALUES
  ('3dm', 1),
  ('3ds', 1),
  ('a2c', 2),
  ('apt', 3),
  ('asm', 4),
  ('asm', 5),
  ('asm', 6),
  ('asp', 7),
  ('asp', 8),
  ('ccd', 9),
  ('cdd', 10),
  ('cdw', 11),
  ('cdw', 12),
  ('cpp', 13),
  ('cr2', 1),
  ('dgn', 1),
  ('dtd', 1),
  ('dwg', 1),
  ('dwg', 1),
  ('dxf', 1),
  ('ics', 1),
  ('igs', 1),
  ('igs', 1),
  ('iso', 1),
  ('iso', 1),
  ('ma', 1),
  ('max', 1),
  ('max', 1),
  ('mb', 1),
  ('mod', 1),
  ('mod', 1),
  ('mod', 1),
  ('mod', 1),
  ('mts', 1),
  ('obj', 1),
  ('part', 1),
  ('pkg', 1),
  ('prj', 1),
  ('pwi', 1),
  ('rnd', 1),
  ('sldasm', 1),
  ('sldprt', 1),
  ('stl', 1),
  ('vcd', 1),
  ('vob', 1),
  ('wm', 1),
  ('wm2d', 1);

INSERT INTO file_ref (uuid, uuid_file_parent, hash, uuid_user, filename, content_type, id_ext, filesize , path_file, created_at, updated_at) VALUES
  ('bc1c2151-86d0-4656-9c9d-d016dd584297', 'bc1c2151-86d0-4656-9c9d-d016dd584297', E'\\000', '31ecc6f8-0c09-4a59-a2d5-34b5b833e59b', 'filename', 'text/plain', 1, 0, 'path/file/file.txt', now(), now()),
  ('3706d1a1-80ae-4367-be39-af7091373811', 'bc1c2151-86d0-4656-9c9d-d016dd584297', E'\\xe3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', '68b8281a-d19c-4d4b-88eb-6fd4a2afde1b', 'file_child_two.pdd', 'text/plain', 1, 136, '/sholder/file/f1c5a362-55f9-4edb-ad90-a2ea64d586df', now(), now());

INSERT INTO actual_status_ref (name) VALUES
  ('Developed'),
  ('Tested'),
  ('Planned'),
  ('Launched'),
  ('Discontinued');

INSERT INTO type_access_ref (name) VALUES
  ('Private'),
  ('Protected'),
  ('Public');

-- TABLE: param_ref: id (serial), paramname (VARCHAR(100))
INSERT INTO param_ref (paramname) VALUES
  ('Index'),
  ('Selector'),
  ('Part Number'),
  ('Description'),
  ('E-Shop link'),
  ('Material'),
  ('Finish'),
  ('Article Number'),
  ('Nominal Ø'),
  ('Pitch (mm)'),
  ('Length (mm)'),
  ('Head height (mm)');

-- TABLE: language_ref: id (SERIAL), lang (VARCHAR(100)), langshort (VARCHAR(10))
INSERT INTO language_ref (lang, langshort) VALUES
  ('Russian', 'RU'),
  ('English', 'EN');

-- TABLE: param_translate_list: id (serial), id_param (INTEGER), id_lang (INTEGER),
-- param (VARCHAR(225))
INSERT INTO param_translate_list (id_param, id_lang, param) VALUES
  (1, 1, 'Индекс');

-- TABLE: spec_translate_list: id (serial), id_spec (INTEGER), id_lang (INTEGER),
-- spec (VARCHAR(225))
INSERT INTO spec_translate_list (id_spec, id_lang, spec) VALUES
  (1, 1, 'Root');

-- TABLE: region_ref: id (serial), region (varying(100))
INSERT INTO region_ref (region) VALUES
  ('Республика Адыгея (Адыгея)'),
  ('Республика Башкортостан'),
  ('Республика Бурятия'),
  ('Республика Алтай'),
  ('Республика Дагестан'),
  ('Республика Ингушетия'),
  ('Кабардино-Балкарская Республика'),
  ('Республика Калмыкия'),
  ('Карачаево-Черкесская Республика'),
  ('Республика Карелия'),
  ('Республика Коми'),
  ('Республика Марий Эл'),
  ('Республика Мордовия'),
  ('Республика Саха (Якутия)'),
  ('Республика Северная Осетия - Алания'),
  ('Республика Татарстан (Татарстан)'),
  ('Республика Тыва'),
  ('Удмуртская Республика'),
  ('Республика Хакасия'),
  ('Чеченская Республика'),
  ('Чувашская Республика - Чувашия'),
  ('Алтайский край'),
  ('Краснодарский край'),
  ('Красноярский край'),
  ('Приморский край'),
  ('Ставропольский край'),
  ('Хабаровский край'),
  ('Амурская область'),
  ('Архангельская область'),
  ('Астраханская область'),
  ('Белгородская область'),
  ('Брянская область'),
  ('Владимирская область'),
  ('Волгоградская область'),
  ('Вологодская область'),
  ('Воронежская область'),
  ('Ивановская область'),
  ('Иркутская область'),
  ('Калининградская область'),
  ('Калужская область'),
  ('Камчатский край'),
  ('Кемеровская область - Кузбасс'),
  ('Кировская область'),
  ('Костромская область'),
  ('Курганская область'),
  ('Курская область'),
  ('Ленинградская область'),
  ('Липецкая область'),
  ('Магаданская область'),
  ('Московская область'),
  ('Мурманская область'),
  ('Нижегородская область'),
  ('Новгородская область'),
  ('Новосибирская область'),
  ('Омская область'),
  ('Оренбургская область'),
  ('Орловская область'),
  ('Пензенская область'),
  ('Пермский край'),
  ('Псковская область'),
  ('Ростовская область'),
  ('Рязанская область'),
  ('Самарская область'),
  ('Саратовская область'),
  ('Сахалинская область'),
  ('Свердловская область'),
  ('Смоленская область'),
  ('Тамбовская область'),
  ('Тверская область'),
  ('Томская область'),
  ('Тульская область'),
  ('Тюменская область'),
  ('Ульяновская область'),
  ('Челябинская область'),
  ('Забайкальский край'),
  ('Ярославская область'),
  ('г. Москва'),
  ('Санкт-Петербург'),
  ('Еврейская автономная область'),
  ('Ненецкий автономный округ'),
  ('Ханты-Мансийский автономный округ - Югра'),
  ('Чукотский автономный округ'),
  ('Ямало-Ненецкий автономный округ'),
  ('Республика Крым'),
  ('Севастополь'),
  ('Иные территории, включая город и космодром Байконур');

-- TABLE: type_of_change_ref: id (serial), type_of_change (VARCHAR(100))
INSERT INTO type_of_change_ref (type_of_change) VALUES
  ('data update');

-- TABLE: spec_ref: id (serial), spec (VARCHAR(100)), id_spec_parent (INTEGER)
INSERT INTO spec_ref (spec, id_spec_parent) VALUES
  ('ROOT', 1);
